---
title: 'STOR 455 Homework #9'
subtitle: "25 points - Due 11/28 at 11:59pm"
output:
  word_document: default
  html_document:
    df_print: paged
  pdf_document: default
---

__Situation:__ Can we predict income by education level? For this assignment, you will practice building polynomial models through predicting income by education level using data from Elections16 in the Stat2Data dataset. 
 
__Data Source:__ To get the election data, begin with the Election16 data from Stat2Data. The data contains information from all 50 states and the District of Columbia for the 2016 U.S. presidential election. It is similar to Election08 for the 2008 election. 

#### Polynomial Models: ####
1. Calculate the least squares regression line (linear model) that best fits your data using Percent college grads (BA) as the predictor and Income as the response. Interpret (in context) what the slope estimate tells you about income and percent college grads. Include a summary output for your model.

2. Fit a quadratic model using Percent college grads (BA) to predict Income and examine the residuals. Construct a scatterplot of the data with the quadratic fit included. Include a brief discussion of the linear model conditions. 

3. Did the fit improve significantly in question 2 by including the quadratic term? Justify your answer.

4. Fit a complete second order model for predicting Income based on Percent college grads (BA) and TrumpWin and examine the residuals. Discuss each of the linear model conditions. 

5. Perform a hypothesis test to determine the importance of just the terms that involve Percent college grads (BA) in the model constructed in question 4. List your hypotheses, p-value, and conclusion. 