---
title: 'STOR 455 Homework #9'
subtitle: "25 points - Due 11/28 at 11:59pm"
output:
  word_document: default
  html_document:
    df_print: paged
  pdf_document: default
---

# ============================================
# Set-up
# ============================================
```{r}
library(Stat2Data)
library(metRology)
library(mosaic)
library(tidyr)
library(corrplot)
library(leaps)
library(car)
library(polynom)
library(readr)
library(dplyr)
library(bestglm)
library(MASS)
source("https://raw.githubusercontent.com/JA-McLean/STOR455/master/scripts/ShowSubsets.R")
source("https://raw.githubusercontent.com/JA-McLean/STOR455/master/scripts/anova455.R")
```

# ============================================
# Problems
# ============================================
```{r}
data("Election16")
head(Election16)
```
a) Create a linear model to predict income in a state based on Trump winning and one other factor.

```{r}
mod1 = lm(Income~TrumpWin + Adv + TrumpWin*Adv, data = Election16)
plot(Income~TrumpWin, data = Election16)
abline(mod1)
summary(mod1)
```
b) Conditions ?
```{r}

```

c) Make a polynomial model to predict income in a state based on Trump winning.
```{r}

```

