---
title: 'STOR 455 Homework #9'
subtitle: "25 points - Due 11/28 at 11:59pm"
output:
  word_document: default
  html_document:
    df_print: paged
  pdf_document: default
---

__Situation:__ For this assignment, you will practice constructing and interpreting Two Way ANOVA models. 

__Data Source:__ To get the data, begin with the BirdNest data from Stat2Data. The data contains nest and species characteristics for North American passerines.

#### Two Way ANOVA: ####
1. Construct an ANOVA model for mean length of time spent in incubation (Incubate) using the location (Location) and nest type (Nesttype) as predictors (without an interaction). Include output showing the ANOVA table; state hypotheses and provide a conclusion in the context of your data. If your ANOVA model indicates there are significant differences among the pupil dilation means: Discuss where the significant differences occur using Tukey HSD methods. 

2. Produce plots and/or summary statistics to comment on the appropriateness of the following conditions for your data: normality of residuals, and equality of the variances. 

3. Construct an ANOVA model for mean length of time spent in incubation (Incubate) using the location (Location) and nest type (Nesttype) as predictors with the interaction. Include the output showing the ANOVA table; state hypotheses and provide a conclusion in the context of your data. If your ANOVA indicates that there are significant differences among the pupil dilation means: Discuss where the signficant differences occur using Tukey HSD methods. 